include/utils.h File Reference
Includes Necessary utilities functions.
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
Macros
#define MAX_FACTORIAL_INPUT 20
#define FLAG_FORCE_LOOKUP 0x01
#define FLAG_FORCE_GAMMA 0x02
#define FLAG_FORCE_STIRLING 0x04
#define FLAG_PREFER_EXACT 0x08
Functions
bool lut_factorial (int n, uint64_t *result)
Computes factorial using a lookup table for optimal performance.
bool gamma_factorial (double_t n, double_t *result)
Computes factorial using the gamma function for extended range.
bool stirlings_factorial (double_t n, double_t *result)
Computes factorial approximation using Stirling's formula.
bool factorial (double_t n, double_t *result, uint8_t flags)
Unified factorial dispatcher.
Variables
static const uint64_t FACTORIAL_LUT [21]
Detailed Description
Includes Necessary utilities functions.
Date
22/06/25
Definition in file utils.h.
Macro Definition Documentation
FLAG_FORCE_GAMMA
#define FLAG_FORCE_GAMMA 0x02
Definition at line 18 of file utils.h.
Referenced by factorial().
FLAG_FORCE_LOOKUP
#define FLAG_FORCE_LOOKUP 0x01
Definition at line 17 of file utils.h.
Referenced by factorial().
FLAG_FORCE_STIRLING
#define FLAG_FORCE_STIRLING 0x04
Definition at line 19 of file utils.h.
Referenced by factorial().
FLAG_PREFER_EXACT
#define FLAG_PREFER_EXACT 0x08
Definition at line 20 of file utils.h.
Referenced by factorial().
MAX_FACTORIAL_INPUT
#define MAX_FACTORIAL_INPUT 20
Definition at line 15 of file utils.h.
Function Documentation
factorial()
bool factorial (double_t n, double_t * result, uint8_t flags)
Unified factorial dispatcher.
Parameters
n Input number
result Output pointer
flags Control flags:
0x01: Force lookup table
0x02: Force gamma function
0x04: Force Stirling's
0x08: Prefer exact results
Returns
true on success
Definition at line 49 of file utils.c.
References FLAG_FORCE_GAMMA, FLAG_FORCE_LOOKUP, FLAG_FORCE_STIRLING, FLAG_PREFER_EXACT, gamma_factorial(), lut_factorial(), and stirlings_factorial().
gamma_factorial()
bool gamma_factorial (double_t n, double_t * result)
Computes factorial using the gamma function for extended range.
Parameters
   n Input value (n >= 0)
out result Pointer to store the computed result
Returns
bool True if successful, false on error/overflow
Note
Features:
Uses tgamma() from math.h (Γ(n+1) = n!)
Supports non-integer values through gamma function
More precise than Stirling's approximation
handles edge cases and overflow proection
Warning
:
Slightly slower than lookup table
Limited by floating-point precision
Returns false for negative inputs
Computes factorial using the gamma function for extended range.
Definition at line 21 of file utils.c.
Referenced by factorial().
lut_factorial()
bool lut_factorial (int n, uint64_t * result)
Computes factorial using a lookup table for optimal performance.
Parameters
   n Input value (0 <= n <= 20 for exact results)
out result Pointer to store the computed result
Returns
bool True if successful, false if overflow/invalid input
Note
Features:
O(1) lookup time for n <= 20
Hardcoded exact values for 0! to 20!
Immediate rejection of invalid inputs
Warning
Returns false for:
Negative inputs
n > 20 (would overflow uint64_t)
Computes factorial using a lookup table for optimal performance.
Definition at line 12 of file utils.c.
References FACTORIAL_LUT.
Referenced by factorial().
stirlings_factorial()
bool stirlings_factorial (double_t n, double_t * result)
Computes factorial approximation using Stirling's formula.
Parameters
   n Input value (n >= 0)
out result Pointer to store the approximated result
Returns
bool True if successful, false on invalid input
Note
Features:
O(1) computation time
Good approximation for n > 20
Uses sqrt(2πn)*(n/e)^n*(1 + 1/(12n))
Warning
:
Approximation error decreases as n increases
Not suitable for exact integer results
Returns false for negative inputs
Computes factorial approximation using Stirling's formula.
Definition at line 33 of file utils.c.
Referenced by factorial().
Variable Documentation
FACTORIAL_LUT
const uint64_t FACTORIAL_LUT[21] [static]
Initial value:
= {
    1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800,
    39916800, 479001600, 6227020800, 87178291200, 1307674368000,
    20922789888000, 355687428096000, 6402373705728000,
    121645100408832000, 2432902008176640000
}
Definition at line 23 of file utils.h.
Referenced by lut_factorial().