src/utils.c File Reference
Comprehensive factorial computation with multiple methods.
#include "utils.h"
Functions
bool lut_factorial (int n, uint64_t *result)
Exact factorial using lookup table (0-20)
bool gamma_factorial (double_t n, double_t *result)
Factorial via gamma function (supports non-integers)
bool stirlings_factorial (double_t n, double_t *result)
Factorial approximation using Stirling's formula.
bool factorial (double_t n, double_t *result, uint8_t flags)
Unified factorial dispatcher.
Detailed Description
Comprehensive factorial computation with multiple methods.
Date
22/06/25
Definition in file utils.c.
Function Documentation
factorial()
bool factorial (double_t n, double_t * result, uint8_t flags)
Unified factorial dispatcher.
Parameters
n Input number
result Output pointer
flags Control flags:
0x01: Force lookup table
0x02: Force gamma function
0x04: Force Stirling's
0x08: Prefer exact results
Returns
true on success
Definition at line 49 of file utils.c.
References FLAG_FORCE_GAMMA, FLAG_FORCE_LOOKUP, FLAG_FORCE_STIRLING, FLAG_PREFER_EXACT, gamma_factorial(), lut_factorial(), and stirlings_factorial().
gamma_factorial()
bool gamma_factorial (double_t n, double_t * result)
Factorial via gamma function (supports non-integers)
Computes factorial using the gamma function for extended range.
Definition at line 21 of file utils.c.
Referenced by factorial().
lut_factorial()
bool lut_factorial (int n, uint64_t * result)
Exact factorial using lookup table (0-20)
Computes factorial using a lookup table for optimal performance.
Definition at line 12 of file utils.c.
References FACTORIAL_LUT.
Referenced by factorial().
stirlings_factorial()
bool stirlings_factorial (double_t n, double_t * result)
Factorial approximation using Stirling's formula.
Computes factorial approximation using Stirling's formula.
Definition at line 33 of file utils.c.
Referenced by factorial().