include/vector.h File Reference
Includes core vector functionalities.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <math.h>
Classes
struct Vector
Vector structure containing elements and metadata.
Macros
#define VECTOR_MIN_CAPACITY 16
Minimum capacity when vector is created.
#define VECTOR_GROWTH_FACTOR 2
Growth factor when resizing vector.
Enumerations
enum VectorError {
VECTOR_SUCCESS = 0
, VECTOR_ERROR_NULL
, VECTOR_ERROR_MEM
, VECTOR_ERROR_INIT
,
VECTOR_ERROR_SIZE
, VECTOR_ERROR_MATH
, VECTOR_ERROR_INDEX
, VECTOR_ERROR_INVALID_ARG
,
VECTOR_ERROR_READONLY
 }
Functions
bool vector_valid (const Vector *vector)
Check if a vector is valid (non-null and has allocated elements)
int vector_create (size_t size, Vector **out_vector)
Create a new vector with specified size.
int vector_init (Vector *vector, size_t size)
Initialize an existing vector with specified size.
int vector_zero (Vector *vector)
Set all elements of vector to zero.
int vector_resize_zero (Vector *vector, size_t size)
Resize vector and zero all elements.
int vector_create_zero (size_t size, Vector **out_vector)
Create a new zero-initialized vector.
int vector_from_array (const double_t *arr, size_t size, Vector **out_vector)
Create vector from C array.
int vector_copy (const Vector *src, Vector *dest)
Copy contents of source vector to destination vector.
int vector_free (Vector *vector)
Free memory allocated by vector.
int vector_resize (Vector *vector, size_t size)
Resize vector to specified size.
int vector_reserve (Vector *vector, size_t capacity)
Reserve capacity for vector.
int vector_shrink_to_fit (Vector *vector)
Reduce capacity to match size.
int vector_get (const Vector *vector, size_t index, double_t *out_val)
Get element at specified index.
int vector_set (Vector *vector, size_t index, double_t val)
Set element at specified index.
int vector_data (const Vector *vector, const double_t **out_data)
Get pointer to underlying element array.
int vector_mutable_data (Vector *vector, double_t **out_data)
Get mutable pointer to underlying element array.
int vector_size (const Vector *vector, size_t *out_size)
Get current size of vector.
int vector_capacity (const Vector *vector, size_t *out_capacity)
Get current capacity of vector.
int vector_2d (double_t x, double_t y, Vector **out_vector)
Create 2D vector.
int vector_3d (double_t x, double_t y, double_t z, Vector **out_vector)
Create 3D vector.
int vector_4d (double_t x, double_t y, double_t z, double_t w, Vector **out_vector)
Create 4D vector.
int vector_add (const Vector *a, const Vector *b, Vector *result)
Element-wise vector addition (result = a + b)
int vector_sub (const Vector *a, const Vector *b, Vector *result)
Element-wise vector subtraction (result = a - b)
int vector_scale (const Vector *a, double_t scaler, Vector *result)
Vector scaling (result = a * scalar)
int vector_mult (const Vector *a, const Vector *b, Vector *result)
Element-wise vector multiplication (result = a * b)
int vector_div (const Vector *a, const Vector *b, Vector *result)
Element-wise vector division (result = a / b)
int vector_negate (const Vector *a, Vector *result)
Vector negation (result = -a)
int vector_dot (const Vector *a, const Vector *b, double_t *result)
Dot product of two vectors.
int vector_cross (const Vector *a, const Vector *b, Vector *result)
Cross product of two 3D vectors.
int vector_magnitude (const Vector *vector, double_t *result)
Compute magnitude (length) of vector.
int vector_normalize (Vector *vector)
Normalize vector in-place (make unit length)
int vector_distance (const Vector *a, const Vector *b, double_t *result)
Compute Euclidean distance between two vectors.
int vector_angle (const Vector *a, const Vector *b, double_t *result)
Compute angle between two vectors in radians.
int vector_lerp (const Vector *a, const Vector *b, double_t t, Vector *result)
Linear interpolation between two vectors.
int vector_slerp (const Vector *a, const Vector *b, double_t t, Vector *result)
Spherical linear interpolation between two vectors.
int vector_project (const Vector *a, const Vector *b, Vector *result)
Project vector a onto vector b.
int vector_reject (const Vector *a, const Vector *b, Vector *result)
Reject vector a from vector b (component perpendicular to b)
int vector_reflect (const Vector *a, const Vector *b, Vector *result)
Reflect vector a over vector b (like mirror reflection)
int vector_min (const Vector *vector, double_t *min)
Find minimum element in vector.
int vector_max (const Vector *vector, double_t *max)
Find maximum element in vector.
int vector_sum (const Vector *vector, double_t *sum)
Compute sum of all vector elements.
int vector_mean (const Vector *vector, double_t *mean)
Compute mean of vector elements.
int vector_abs (Vector *vector)
Compute absolute value of all elements in-place.
int vector_floor (Vector *vector)
Apply floor function to all elements in-place.
int vector_ceil (Vector *vector)
Apply ceiling function to all elements in-place.
int vector_round (Vector *vector)
Round all elements in-place.
int vector_equals (const Vector *a, const Vector *b, double_t tolerance)
Check if two vectors are equal within tolerance.
int vector_is_zero (const Vector *vector, double_t tolerance)
Check if vector is approximately zero.
int vector_is_unit (const Vector *vector, double_t tolerance)
Check if vector is approximately unit length.
int vector_print (const Vector *vector)
Print vector contents to stdout.
Detailed Description
Includes core vector functionalities.
Date
25/06/25
Definition in file vector.h.
Macro Definition Documentation
VECTOR_GROWTH_FACTOR
#define VECTOR_GROWTH_FACTOR 2
Growth factor when resizing vector.
Definition at line 16 of file vector.h.
Referenced by calculate_new_capacity().
VECTOR_MIN_CAPACITY
#define VECTOR_MIN_CAPACITY 16
Minimum capacity when vector is created.
Definition at line 15 of file vector.h.
Referenced by calculate_new_capacity().
Enumeration Type Documentation
VectorError
enum VectorError
Enumerator
VECTOR_SUCCESS
VECTOR_ERROR_NULL
VECTOR_ERROR_MEM
VECTOR_ERROR_INIT
VECTOR_ERROR_SIZE
VECTOR_ERROR_MATH
VECTOR_ERROR_INDEX
VECTOR_ERROR_INVALID_ARG
VECTOR_ERROR_READONLY
Definition at line 18 of file vector.h.
Function Documentation
vector_2d()
int vector_2d (double_t x, double_t y, Vector ** out_vector)
Create 2D vector.
Parameters
   x X component
   y Y component
out out_vector Pointer to receive new vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The caller owns the returned vector and must free it with vector_free()
Definition at line 265 of file vector.c.
References vector_create(), VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_3d()
int vector_3d (double_t x, double_t y, double_t z, Vector ** out_vector)
Create 3D vector.
Parameters
   x X component
   y Y component
   z Z component
out out_vector Pointer to receive new vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The caller owns the returned vector and must free it with vector_free()
Definition at line 279 of file vector.c.
References vector_create(), VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_4d()
int vector_4d (double_t x, double_t y, double_t z, double_t w, Vector ** out_vector)
Create 4D vector.
Parameters
   x X component
   y Y component
   z Z component
   w W component
out out_vector Pointer to receive new vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The caller owns the returned vector and must free it with vector_free()
Definition at line 294 of file vector.c.
References vector_create(), VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_abs()
int vector_abs (Vector * vector)
Compute absolute value of all elements in-place.
Parameters
vector Vector to modify
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 837 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_add()
int vector_add (const Vector * a, const Vector * b, Vector * result)
Element-wise vector addition (result = a + b)
Parameters
   a First operand
   b Second operand
out result Vector to store result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 316 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_angle()
int vector_angle (const Vector * a, const Vector * b, double_t * result)
Compute angle between two vectors in radians.
Parameters
   a First vector
   b Second vector
out result Pointer to store angle
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if either vector has zero length
Definition at line 551 of file vector.c.
References Vector::size, vector_dot(), VECTOR_ERROR_INIT, VECTOR_ERROR_MATH, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, vector_magnitude(), VECTOR_SUCCESS, and vector_valid().
vector_capacity()
int vector_capacity (const Vector * vector, size_t * out_capacity)
Get current capacity of vector.
Parameters
   vector Vector to query
out out_capacity Pointer to receive capacity
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 256 of file vector.c.
References Vector::capacity, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_ceil()
int vector_ceil (Vector * vector)
Apply ceiling function to all elements in-place.
Parameters
vector Vector to modify
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 888 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_copy()
int vector_copy (const Vector * src, Vector * dest)
Copy contents of source vector to destination vector.
Parameters
src Source vector to copy from
dest Destination vector to copy to
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Destination vector will be resized to match source
Definition at line 108 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, vector_init(), VECTOR_SUCCESS, and vector_valid().
vector_create()
int vector_create (size_t size, Vector ** out_vector)
Create a new vector with specified size.
Parameters
   size Initial size of vector
out out_vector Pointer to receive newly created vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The caller owns the returned vector and must free it with vector_free()
Definition at line 25 of file vector.c.
References Vector::capacity, Vector::elements, Vector::size, VECTOR_ERROR_MEM, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
Referenced by vector_2d(), vector_3d(), vector_4d(), vector_create_zero(), vector_from_array(), and vector_reflect().
vector_create_zero()
int vector_create_zero (size_t size, Vector ** out_vector)
Create a new zero-initialized vector.
Parameters
   size Size of vector to create
out out_vector Pointer to receive newly created vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The caller owns the returned vector and must free it with vector_free()
Definition at line 87 of file vector.c.
References vector_create(), VECTOR_SUCCESS, and vector_zero().
vector_cross()
int vector_cross (const Vector * a, const Vector * b, Vector * result)
Cross product of two 3D vectors.
Parameters
   a First vector (must be 3D)
   b Second vector (must be 3D)
out result Vector to store result (must be 3D)
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 456 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_data()
int vector_data (const Vector * vector, const double_t ** out_data)
Get pointer to underlying element array.
Parameters
   vector Vector to access
out out_data Pointer to receive element array
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The returned pointer is owned by the vector and becomes invalid if the vector is resized or freed
Definition at line 229 of file vector.c.
References Vector::elements, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_distance()
int vector_distance (const Vector * a, const Vector * b, double_t * result)
Compute Euclidean distance between two vectors.
Parameters
   a First vector
   b Second vector
out result Pointer to store distance
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 528 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_div()
int vector_div (const Vector * a, const Vector * b, Vector * result)
Element-wise vector division (result = a / b)
Parameters
   a First operand
   b Second operand
out result Vector to store result
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if any element of b is zero
Definition at line 372 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_MATH, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_dot()
int vector_dot (const Vector * a, const Vector * b, double_t * result)
Dot product of two vectors.
Parameters
   a First vector
   b Second vector
out result Pointer to store dot product result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 405 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
Referenced by vector_angle(), vector_magnitude(), vector_project(), and vector_slerp().
vector_equals()
int vector_equals (const Vector * a, const Vector * b, double_t tolerance)
Check if two vectors are equal within tolerance.
Parameters
a First vector
b Second vector
tolerance Maximum allowed difference per element
Returns
VECTOR_SUCCESS if equal within tolerance, error code otherwise
Definition at line 941 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_floor()
int vector_floor (Vector * vector)
Apply floor function to all elements in-place.
Parameters
vector Vector to modify
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 862 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_free()
int vector_free (Vector * vector)
Free memory allocated by vector.
Parameters
vector Vector to free
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Frees both the vector structure and its elements
After calling, the vector pointer is no longer valid
Definition at line 123 of file vector.c.
References Vector::elements, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
Referenced by vector_reflect().
vector_from_array()
int vector_from_array (const double_t * arr, size_t size, Vector ** out_vector)
Create vector from C array.
Parameters
   arr Source array
   size Number of elements in array
out out_vector Pointer to receive newly created vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The caller owns the returned vector and must free it with vector_free()
Definition at line 95 of file vector.c.
References vector_create(), VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_get()
int vector_get (const Vector * vector, size_t index, double_t * out_val)
Get element at specified index.
Parameters
   vector Vector to access
   index Index of element to get
out out_val Pointer to receive element value
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 205 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INDEX, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_init()
int vector_init (Vector * vector, size_t size)
Initialize an existing vector with specified size.
Parameters
vector Vector to initialize
size Initial size of vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
This will free any existing elements in the vector
Definition at line 49 of file vector.c.
References Vector::capacity, Vector::elements, Vector::size, VECTOR_ERROR_MEM, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
Referenced by vector_copy().
vector_is_unit()
int vector_is_unit (const Vector * vector, double_t tolerance)
Check if vector is approximately unit length.
Parameters
vector Vector to check
tolerance Maximum allowed deviation from 1.0
Returns
VECTOR_SUCCESS if |magnitude-1| <= tolerance, error code otherwise
Definition at line 978 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_MATH, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_is_zero()
int vector_is_zero (const Vector * vector, double_t tolerance)
Check if vector is approximately zero.
Parameters
vector Vector to check
tolerance Maximum allowed element magnitude
Returns
VECTOR_SUCCESS if all elements <= tolerance, error code otherwise
Definition at line 961 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_lerp()
int vector_lerp (const Vector * a, const Vector * b, double_t t, Vector * result)
Linear interpolation between two vectors.
Parameters
   a Start vector
   b End vector
   t Interpolation factor (0=a, 1=b)
out result Vector to store interpolated result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 579 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
Referenced by vector_slerp().
vector_magnitude()
int vector_magnitude (const Vector * vector, double_t * result)
Compute magnitude (length) of vector.
Parameters
   vector Vector to measure
out result Pointer to store magnitude
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 477 of file vector.c.
References vector_dot(), VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
Referenced by vector_angle(), and vector_normalize().
vector_max()
int vector_max (const Vector * vector, double_t * max)
Find maximum element in vector.
Parameters
   vector Vector to search
out max Pointer to store maximum value
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 771 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_mean()
int vector_mean (const Vector * vector, double_t * mean)
Compute mean of vector elements.
Parameters
   vector Vector to analyze
out mean Pointer to store mean value
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if vector is empty
Definition at line 819 of file vector.c.
References Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, vector_sum(), and vector_valid().
vector_min()
int vector_min (const Vector * vector, double_t * min)
Find minimum element in vector.
Parameters
   vector Vector to search
out min Pointer to store minimum value
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 742 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_mult()
int vector_mult (const Vector * a, const Vector * b, Vector * result)
Element-wise vector multiplication (result = a * b)
Parameters
   a First operand
   b Second operand
out result Vector to store result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 358 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_mutable_data()
int vector_mutable_data (Vector * vector, double_t ** out_data)
Get mutable pointer to underlying element array.
Parameters
   vector Vector to access
out out_data Pointer to receive element array
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
The returned pointer is owned by the vector and becomes invalid if the vector is resized or freed
Definition at line 239 of file vector.c.
References Vector::elements, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_negate()
int vector_negate (const Vector * a, Vector * result)
Vector negation (result = -a)
Parameters
   a Vector to negate
out result Vector to store result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 388 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_normalize()
int vector_normalize (Vector * vector)
Normalize vector in-place (make unit length)
Parameters
vector Vector to normalize
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if vector has zero length
Definition at line 493 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_MATH, VECTOR_ERROR_NULL, vector_magnitude(), VECTOR_SUCCESS, and vector_valid().
vector_print()
int vector_print (const Vector * vector)
Print vector contents to stdout.
Parameters
vector Vector to print
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 995 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_project()
int vector_project (const Vector * a, const Vector * b, Vector * result)
Project vector a onto vector b.
Parameters
   a Vector to project
   b Vector to project onto
out result Vector to store projection result
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if b has zero length
Definition at line 651 of file vector.c.
References Vector::elements, Vector::size, vector_dot(), VECTOR_ERROR_INIT, VECTOR_ERROR_MATH, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
Referenced by vector_reflect(), and vector_reject().
vector_reflect()
int vector_reflect (const Vector * a, const Vector * b, Vector * result)
Reflect vector a over vector b (like mirror reflection)
Parameters
   a Vector to reflect
   b Vector to reflect over
out result Vector to store reflection result
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if b has zero length
Definition at line 708 of file vector.c.
References Vector::elements, Vector::size, vector_create(), VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, vector_free(), vector_project(), VECTOR_SUCCESS, and vector_valid().
vector_reject()
int vector_reject (const Vector * a, const Vector * b, Vector * result)
Reject vector a from vector b (component perpendicular to b)
Parameters
   a Vector to reject
   b Vector to reject from
out result Vector to store rejection result
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Returns VECTOR_ERROR_MATH if b has zero length
Definition at line 683 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, vector_project(), VECTOR_SUCCESS, and vector_valid().
vector_reserve()
int vector_reserve (Vector * vector, size_t capacity)
Reserve capacity for vector.
Parameters
vector Vector to modify
capacity Minimum capacity to reserve
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Does not change vector size, only allocated capacity
Definition at line 161 of file vector.c.
References Vector::capacity, Vector::elements, VECTOR_ERROR_MEM, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_resize()
int vector_resize (Vector * vector, size_t size)
Resize vector to specified size.
Parameters
vector Vector to resize
size New size for vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
If growing, new elements are uninitialized
Definition at line 134 of file vector.c.
References calculate_new_capacity(), Vector::capacity, Vector::elements, Vector::size, VECTOR_ERROR_MEM, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
Referenced by vector_resize_zero().
vector_resize_zero()
int vector_resize_zero (Vector * vector, size_t size)
Resize vector and zero all elements.
Parameters
vector Vector to resize
size New size for vector
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 74 of file vector.c.
References Vector::elements, VECTOR_ERROR_NULL, vector_resize(), and VECTOR_SUCCESS.
vector_round()
int vector_round (Vector * vector)
Round all elements in-place.
Parameters
vector Vector to modify
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 915 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_scale()
int vector_scale (const Vector * a, double_t scaler, Vector * result)
Vector scaling (result = a * scalar)
Parameters
   a Vector to scale
   scaler Scaling factor
out result Vector to store result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 344 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_set()
int vector_set (Vector * vector, size_t index, double_t val)
Set element at specified index.
Parameters
vector Vector to modify
index Index of element to set
val Value to set
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 217 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INDEX, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
vector_shrink_to_fit()
int vector_shrink_to_fit (Vector * vector)
Reduce capacity to match size.
Parameters
vector Vector to shrink
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 177 of file vector.c.
References Vector::capacity, Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_MEM, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_size()
int vector_size (const Vector * vector, size_t * out_size)
Get current size of vector.
Parameters
   vector Vector to query
out out_size Pointer to receive size
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 249 of file vector.c.
References Vector::size, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
vector_slerp()
int vector_slerp (const Vector * a, const Vector * b, double_t t, Vector * result)
Spherical linear interpolation between two vectors.
Parameters
   a Start vector (should be normalized)
   b End vector (should be normalized)
   t Interpolation factor (0=a, 1=b)
out result Vector to store interpolated result
Returns
VECTOR_SUCCESS on success, error code otherwise
Note
Falls back to linear interpolation if vectors are nearly parallel
Definition at line 610 of file vector.c.
References Vector::elements, Vector::size, vector_dot(), VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, vector_lerp(), VECTOR_SUCCESS, and vector_valid().
vector_sub()
int vector_sub (const Vector * a, const Vector * b, Vector * result)
Element-wise vector subtraction (result = a - b)
Parameters
   a First operand
   b Second operand
out result Vector to store result
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 330 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_ERROR_SIZE, VECTOR_SUCCESS, and vector_valid().
vector_sum()
int vector_sum (const Vector * vector, double_t * sum)
Compute sum of all vector elements.
Parameters
   vector Vector to sum
out sum Pointer to store sum
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 798 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, VECTOR_SUCCESS, and vector_valid().
Referenced by vector_mean().
vector_valid()
bool vector_valid (const Vector * vector)
Check if a vector is valid (non-null and has allocated elements)
Parameters
vector Pointer to vector to check
Returns
true if vector is valid, false otherwise
Definition at line 12 of file vector.c.
References Vector::elements.
Referenced by vector_abs(), vector_add(), vector_angle(), vector_ceil(), vector_copy(), vector_cross(), vector_data(), vector_distance(), vector_div(), vector_dot(), vector_equals(), vector_floor(), vector_get(), vector_is_unit(), vector_is_zero(), vector_lerp(), vector_magnitude(), vector_max(), vector_mean(), vector_min(), vector_mult(), vector_mutable_data(), vector_negate(), vector_normalize(), vector_print(), vector_project(), vector_reflect(), vector_reject(), vector_round(), vector_scale(), vector_set(), vector_slerp(), vector_sub(), and vector_sum().
vector_zero()
int vector_zero (Vector * vector)
Set all elements of vector to zero.
Parameters
vector Vector to zero
Returns
VECTOR_SUCCESS on success, error code otherwise
Definition at line 64 of file vector.c.
References Vector::elements, Vector::size, VECTOR_ERROR_INIT, VECTOR_ERROR_NULL, and VECTOR_SUCCESS.
Referenced by vector_create_zero().